name: HakPay APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          cache: true

      - name: Android Yapılandırması
        run: |
          rm -rf android
          flutter create . --project-name hakpay --org com.hakpay --platforms=android
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i '/<\/application>/i \        <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3940256099942544~3347511713"/>' $MANIFEST

      - name: APK Derle
        run: |
          flutter pub get
          flutter build apk --release --no-tree-shake-icons

      - uses: actions/upload-artifact@v4
        with:
          name: hakpay-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
